<a href="https://colab.research.google.com/github/dineshdilip2/Dinesh-K/blob/main/Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
!git clone https://github.com/dineshdilip2/Dinesh-K.git

Cloning into 'Dinesh-K'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.


# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
import numpy as np
print(np.__version__)

np.show_config()


1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
import numpy as np
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
memory_size = array.nbytes

print(memory_size)

40


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
import numpy as np
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  **Calling ufuncs:** ``op(*x[, out], where=True, **kwargs)``
 |  
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array object(s) in whic

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
import numpy as np
vec = np.zeros(10)
vec[4]=1
print(vec)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
import numpy as np
vec = np.arange(10,50,1)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
import numpy as np
#create a vector with values ranging from 10 to 49
vec =np.arange(10,50,1)
#rerverse the vector
rev_vec =vec[::-1]
print(rev_vec)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
import numpy as np

#create a vector with values ranging from 0 to 8
vec = np.arange(9)
#reshape the vector into 3*3 matrix
matrix = vec.reshape((3,3))

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
import numpy as np
arr = np.array([1,2,0,0,4,0])
indices = np.nonzero(arr)[0].tolist()
print(indices)


[0, 1, 4]


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
import numpy as np
matrix=np.eye(3)
print(matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
import numpy as np

arr = np.random.rand(3,3,3)
print(arr)

[[[0.98899517 0.06711112 0.18422594]
  [0.18680085 0.02681206 0.71673523]
  [0.37039702 0.79988547 0.79017039]]

 [[0.93682491 0.44073411 0.09415572]
  [0.49861787 0.54311615 0.22578504]
  [0.50592148 0.75938704 0.7387072 ]]

 [[0.56180108 0.73130275 0.4656308 ]
  [0.36907868 0.40992029 0.62911671]
  [0.85473494 0.81880122 0.8547301 ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
import numpy as np
arr = np.random.rand(10,10)
print(arr)
min_val = np.min(arr)
max_val = np.max(arr)

print(min_val)
print(max_val)

[[0.90178711 0.71590473 0.0654939  0.44326867 0.09884389 0.47937669
  0.98062866 0.85328687 0.87144106 0.46795553]
 [0.39114432 0.62148196 0.30468368 0.23538993 0.22491038 0.90466112
  0.29662302 0.14266941 0.78024945 0.49661375]
 [0.34241163 0.05951732 0.62790374 0.92073114 0.88721463 0.27519147
  0.94296265 0.08684668 0.54327797 0.08234761]
 [0.46108454 0.31096284 0.95150373 0.27678298 0.5971833  0.77119334
  0.70623312 0.47791764 0.62302532 0.86162273]
 [0.4249837  0.47052559 0.03166986 0.40941871 0.59898954 0.80397128
  0.11687938 0.69444105 0.44692511 0.54408177]
 [0.5993465  0.55290587 0.12930658 0.13613886 0.45573483 0.80297554
  0.84064312 0.58475169 0.41106022 0.639757  ]
 [0.31706451 0.69969533 0.59701353 0.66453081 0.02573179 0.62871655
  0.86420159 0.73195504 0.51558615 0.5216547 ]
 [0.60444774 0.97893028 0.11676773 0.09991242 0.91225105 0.05432599
  0.98042902 0.25692441 0.97505009 0.64377264]
 [0.3800384  0.10608853 0.94914965 0.33124039 0.37615076 0.24118721
  0.85868441

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
import numpy as np
vec = np.random.rand(30)
print(vec)
mean = np.mean(vec)
print({mean})

[0.49325064 0.2647086  0.17649067 0.79489581 0.93683838 0.01592906
 0.87841754 0.60945003 0.21276649 0.59647065 0.34909375 0.87860002
 0.14723924 0.51844884 0.04957023 0.31167726 0.86592677 0.46837283
 0.57398378 0.03999635 0.27091758 0.00597814 0.22645685 0.10288059
 0.57868468 0.0935737  0.93017496 0.62365272 0.88910406 0.69113265]
{0.4531560955102872}


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
import numpy as np

arr =np.ones((5,5))

arr[1:-1,1:-1]=0

print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])

print(arr)

padded_arr =np.pad(arr,pad_width=1,constant_values=0)

print(padded_arr)

[[1 2 3]
 [4 5 6]]
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan=nan
np.nan == np.nan= False
np.inf > np.nan = False
np.nan - np.nan=nan
0.3 == 3 * 0.1=False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
import numpy as np
matrix= np.diag([1,2,3,4],k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
import numpy as np

# Create a 8x8 matrix with all elements set to 0
matrix = np.zeros((8, 8))

# Set the elements at even indices to 1
matrix[::2, ::2] = 1

# Set the elements at odd indices to 1
matrix[1::2, 1::2] = 1

print(matrix)


[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
import numpy as np

shape = (6,7,8)

flat_index = 99

indices = np.unravel_index(flat_index,shape)

print(indices)

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
import numpy as np

block =np.array([[1,0],
                 [0,1]])

matrix =np.tile(block,(4,4))

print(matrix)



[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
import numpy as np

matrix = np.random.rand(5,5)
print(matrix)

#matrix1 = matrix.max()
#print(matrix1)

normalized_matrix=matrix/matrix.max()

print(normalized_matrix)





[[0.39633994 0.94240463 0.23688873 0.6244392  0.67364952]
 [0.34427562 0.06797744 0.12936821 0.58899194 0.25617772]
 [0.79838209 0.7882339  0.1699622  0.87516824 0.25101733]
 [0.80124627 0.31372292 0.00307414 0.09897902 0.35672658]
 [0.86208664 0.71800563 0.96672182 0.97785374 0.97774043]]
[[0.40531618 0.96374805 0.24225375 0.63858139 0.68890622]
 [0.35207271 0.06951698 0.13229812 0.60233133 0.26197959]
 [0.81646371 0.80608569 0.17381147 0.8949889  0.25670233]
 [0.81939276 0.32082806 0.00314376 0.10122068 0.36480567]
 [0.88161103 0.7342669  0.98861597 1.         0.99988413]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
import numpy as np

color_dtype=np.dtype([("r",np.uint8),("g",np.uint8),("b",np.uint8),
                      ("a",np.uint8)])

colors=np.array([(255,0,0,255),(0,255,0,255),(0,0,255,255)],dtype=color_dtype)

print(colors)

[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
import numpy as np

matrix1= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])

print(matrix1)

matrix2=np.array([[1,2],[3,4],[5,6]])

print(matrix2)

result=np.dot(matrix1,matrix2)
print(result)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[1 2]
 [3 4]
 [5 6]]
[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
import numpy as np

array=np.array([1,2,3,4,5,6,7,8,9,10])

print(array)

array[3:9] = -array[3:9]
print(array)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3 -4 -5 -6 -7 -8 -9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [15]:
import numpy as np

print(sum(range(5),-1))
from numpy import *
print(np.sum(range(5),-1))

#Output
#10
#10

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z**Z  is legal
2 << Z >> 2 is legal
Z <- Z is not a valid python expression
1j*Z is legal
Z/1/1 is legal
Z<Z>Z is not a valid python expression

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [16]:
import numpy as np
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-16-c3af468f36f5>:2: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
<ipython-input-16-c3af468f36f5>:3: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [17]:
import numpy as np

array = np.array([-1.7,-1.5,-0.2,0.2,1.5,1.7,2.0])

rounded = np.copysign(np.ceil(np.abs(array)),array)

print(rounded)

[-2. -2. -1.  1.  2.  2.  2.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [18]:
import numpy as np

array1 =np.array([1,2,3,4,5])
array2 =np.array([3,4,5,6,7])

common_values=np.intersect1d(array1,array2)

print(common_values)

[3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [19]:
import numpy as np
import warnings

warnings.simplefilter("ignore",category=UserWarning)

result = np.array([0])/np.array([0])

print(result)

[nan]


<ipython-input-19-4aeb907d87d7>:6: RuntimeWarning: invalid value encountered in true_divide
  result = np.array([0])/np.array([0])


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1) is True

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [23]:
import numpy as np

today = np.datetime64('today')

yesterday = today - np.timedelta64(1,'D')

tomorrow = today + np.timedelta64(1,'D')

print(yesterday)
print(today)
print(tomorrow)

2022-12-28
2022-12-29
2022-12-30


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [24]:
import numpy as np
start = np.datetime64('2016-07-01')

end = np.datetime64('2016-07-31')

dates = np.arange(start,end+1)

print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [31]:
import numpy as np

A =np.array([1,2,3,4,5])
B = np.array([6,7,8,9,10])

np.add(A,B,out=A)

print(A)
np.multiply(A, -A/2, out=A,casting='unsafe')

print(A)

[ 7  9 11 13 15]
[ -24  -40  -60  -84 -112]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [37]:
# 1.Using floor function

import numpy as np

arr =np.random.rand(10)

int_part =np.floor(arr)

print(int_part)

#2.Using integer division

import numpy as np

arr = np.random.rand(10)

int_part = arr//1

print(int_part)

#3.Using the trunc function

import numpy as np

arr = np.random.rand(10)

int_part = np.trunc(arr)

print(int_part)

#4.Using the astype function

import numpy as np

arr = np.random.rand(10)

int_part= arr.astype(int)

print(int_part)

#5.Using round function

arr=  np.random.rand(10)

int_part=np.round(arr)
print(int_part)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]
[0. 0. 1. 0. 1. 0. 1. 0. 1. 0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [43]:
import numpy as np

# Create a 1D array with values ranging from 0 to 4
arr = np.arange(5)

# Reshape the array into a 5x5 matrix
matrix = arr.reshape((5, 5))

print(matrix)


ValueError: ignored

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [44]:
import numpy as np

def generator():
  for i in range(10):
    yield i

arr =np.fromiter(generator(),dtype=int)

print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [45]:
import numpy as np
vec = np.linspace(0,1,10,endpoint=False)

print(vec)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [46]:
import numpy as np

vec =np.random.rand(10)

vec.sort()

print(vec)


[0.0053429  0.0880656  0.33271956 0.35012641 0.47232251 0.50637858
 0.61674287 0.75834669 0.81810884 0.93468239]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [47]:
import numpy as np

arr = np.array([1,2,3,4])

result = np.add.reduce(arr)

print(result)

10


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [49]:
import numpy as np

A = np.random.rand(3,3)
B = np.random.rand(3,3)

#print(A)
#print(B)

result =np.array_equal(A,B)

print(result)


[[0.61570541 0.06873825 0.13319746]
 [0.29051516 0.60230384 0.9051616 ]
 [0.27648145 0.13017429 0.35202616]]
[[0.89746335 0.29463418 0.31825869]
 [0.23327396 0.185281   0.47552371]
 [0.78809698 0.9464236  0.50484167]]
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [51]:
import numpy as np

arr =np.array([1,2,3,4])

arr.flags.writeable = False

try:

  arr[0] = 10
except ValueError as e:
  print(e)  


assignment destination is read-only


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [52]:
import numpy as np

cartesian = np.random.rand(10,2)

polar = np.empty_like(cartesian)
polar[:,0] = np.hypot(cartesian[:,0],cartesian[:,1])
polar[:,1] = np.arctan2(cartesian[:,1],cartesian[:,0])

print(polar)

[[0.89909462 0.18131275]
 [1.2168638  0.66644495]
 [0.29987583 1.06730888]
 [0.91245628 0.34957051]
 [1.28559867 0.70368436]
 [0.79265154 0.74693175]
 [0.12380769 0.77853863]
 [0.59402641 0.31571674]
 [0.3779389  0.15045253]
 [0.94610306 0.77713714]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [58]:
import numpy as np

vec = np.random.rand(10)

index =vec.argmax()
print(vec)
#maximum = vec.amax()

vec[index]=0

print(vec)  

[0.0044741  0.34450136 0.84835162 0.61809469 0.46990438 0.79917276
 0.80344276 0.19901317 0.07836024 0.1092986 ]
[0.0044741  0.34450136 0.         0.61809469 0.46990438 0.79917276
 0.80344276 0.19901317 0.07836024 0.1092986 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [66]:
import numpy as np

x = np.linspace(0,1,11)
y = np.linspace(0,1,11)

X,Y = np.meshgrid(x,y)

structured_array= np.array([(x,y) for x,y in zip(X,Y)],
                           dtype=[('x',float),('y',float)])

print(structured_array)


ValueError: ignored

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [67]:
import numpy as np

X =np.random.rand(5)
Y =np.random.rand(5)

div = np.outer(X,Y)

c = np.reciprocal(div)

print(c)

[[10.8381722  17.7844292   3.04081816 13.70592791  7.43081137]
 [ 3.96207553  6.50139621  1.11162205  5.0104317   2.71645766]
 [15.48124278 25.40327474  4.34350398 19.57754441 10.61416932]
 [ 8.81039567 14.45703713  2.47189384 11.14160632  6.04053774]
 [ 6.83921798 11.22251849  1.91884921  8.6488595   4.68906913]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [73]:
import numpy as np

for dtype in [np.int8,np.int16,np.int32,np.int64,np.uint8,np.uint16,
              np.uint32,np.uint64,
              np.float16,np.float32,np.float64,np.float128,np.complex64,
              np.complex128,np.complex256]:
                info = np.iinfo(dtype)
                print(f"{dtype}: {info.min} {info.max}")

<class 'numpy.int8'>: -128 127
<class 'numpy.int16'>: -32768 32767
<class 'numpy.int32'>: -2147483648 2147483647
<class 'numpy.int64'>: -9223372036854775808 9223372036854775807
<class 'numpy.uint8'>: 0 255
<class 'numpy.uint16'>: 0 65535
<class 'numpy.uint32'>: 0 4294967295
<class 'numpy.uint64'>: 0 18446744073709551615


ValueError: ignored

#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [74]:
import numpy as np

arr = np.random.rand(2,3,4)

flattened_arr= arr.flatten()

for value in flattened_arr:
  print(value)

0.2604153675303523
0.07334974366997526
0.4677748011128191
0.8406498203214611
0.10344846223594095
0.49008233825610137
0.1034810850429716
0.027131914475535424
0.5248726114060629
0.04233079295841102
0.04122623608712128
0.9785419980139382
0.9143846419070237
0.876240394836921
0.4462739078678102
0.5776648650791192
0.1650376989655199
0.6698930072887113
0.36898906107088814
0.014667175495209128
0.5259700291748577
0.1316376859557541
0.4675853559728852
0.5254614866757841


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [76]:
import numpy as np
vec=np.array([1,2,3,4])
scalar = 3.6

idx = np.abs(vec-scalar).argmin()

print(vec[idx])

4


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [77]:
import numpy as np

dtype = np.dtype([('x',np.float),('y',np.float),('r',np.uint8),('g',np.uint8),
                  ('b',np.uint8)])

arr = np.zeros(3,dtype=dtype)

print(arr)

[(0., 0., 0, 0, 0) (0., 0., 0, 0, 0) (0., 0., 0, 0, 0)]


<ipython-input-77-5cbcd6d4382c>:3: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = np.dtype([('x',np.float),('y',np.float),('r',np.uint8),('g',np.uint8),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [79]:
import numpy as np

# Generate a random vector with shape (100, 2) representing coordinates
vec = np.random.rand(100, 2)

# Compute the Euclidean distance between each pair of points
distances = np.linalg.norm(vec[:, None] - vec, axis=-1)

# Print the distances
print(distances)


[[0.         0.72070817 0.84667097 ... 0.76641355 0.56894514 0.61401374]
 [0.72070817 0.         0.19371808 ... 0.43393188 0.50472866 0.51296599]
 [0.84667097 0.19371808 0.         ... 0.33029675 0.48552544 0.47628874]
 ...
 [0.76641355 0.43393188 0.33029675 ... 0.         0.23093311 0.19789498]
 [0.56894514 0.50472866 0.48552544 ... 0.23093311 0.         0.04509715]
 [0.61401374 0.51296599 0.47628874 ... 0.19789498 0.04509715 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [80]:
import numpy as np

# Create a float (32 bits) array
arr = np.array([1.1, 2.2, 3.3, 4.4], dtype=np.float32)

# Create a view of the array with the desired data type
arr_int = arr.view(dtype=np.int32)

# Print the array
print(arr_int)


[1066192077 1074580685 1079194419 1082969293]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [81]:
import numpy as np

# Read the file and create a NumPy array with the data
data = np.loadtxt("data.txt", delimiter=",", missing_values=" ", filling_values=np.nan)

# Print the array
print(data)


TypeError: ignored

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [82]:
import numpy as np

arr =np.array([[1,2,3],[4,5,6]])

for index,element in np.ndenumerate(arr):
   print(index,element)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [84]:
import numpy as np

mean =[0,0]
cov = [[1,0],[0,1]]

x,y  = np.meshgrid(np.linspace(-3,3,100),np.linspace(-3,3,100))

z = np.exp(-0.5 * (np.dot((np.vstack([x, y]) - mean), np.linalg.inv(cov)) * 
    (np.vstack([x, y]) - mean)).sum(axis=0))


print(z)

ValueError: ignored

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [86]:
import numpy as np

# Create an array with zeros
arr = np.zeros((5, 5))

# Set the number of elements to place
p = 3

# Generate p random indices
indices = np.random.random_integers(0, arr.shape[0] - 1, size=p)

# Place the elements in the array
arr[indices, indices] = 1

# Print the array
print(arr)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]]


<ipython-input-86-e0b7faf267bf>:10: DeprecationWarning: This function is deprecated. Please call randint(0, 4 + 1) instead
  indices = np.random.random_integers(0, arr.shape[0] - 1, size=p)


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [87]:
import numpy as np

# Create a matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculate the mean of each row
means = matrix.mean(axis=1)

# Subtract the mean from each row
matrix_mean_subtracted = matrix - means[:, np.newaxis]

# Print the resulting matrix
print(matrix_mean_subtracted)


[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [88]:
import numpy as np 
arr = np.array([[1,4,3],[2,5,6],[7,8,9]])

indices = arr [:,1].argsort()

arr_sorted = arr[indices]

print(arr_sorted)

[[1 4 3]
 [2 5 6]
 [7 8 9]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [89]:
import numpy as np

arr = np.array([[1,0,3],[0,0,6],[7,0,9]])

has_non_zero= np.any(arr,axis=0)

null_columns = np.logical_not(has_non_zero)

print(null_columns)

[False  True False]


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [90]:
import numpy as np

arr = np.array([1,3,5,7,9])

value = 4

diff =  np.abs(arr-value)

index = diff.argmin()

nearest_value =arr[index]

print(nearest_value)


3


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [91]:
import numpy as np

# Create the arrays
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4], [5], [6]])

# Initialize the result array
result = np.zeros((1, 3))

# Iterate over the elements of arr1
for i in range(3):
    # Sum the corresponding elements of arr1 and arr2
    result[0, i] = arr1[0, i] + arr2[i, 0]

# Print the result
print(result)


[[5. 7. 9.]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [92]:
import numpy as np

# Define the array class
class NamedArray(np.ndarray):
    def __new__(cls, array, name):
        # Create a new array from the input array
        obj = np.asarray(array).view(cls)
        # Add the name attribute
        obj.name = name
        return obj
    
    def __array_finalize__(self, obj):
        # Set the name attribute if it is not already set
        if not hasattr(self, 'name'):
            self.name = getattr(obj, 'name', None)

# Create an instance of the array class
arr = NamedArray([1, 2, 3], name='my_array')

# Print the name attribute
print(arr.name)


my_array


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [93]:
import numpy as np

# Define the vectors
vector1 = np.array([1, 2, 3, 4, 5])
vector2 = np.array([1, 2, 2, 4, 4])

# Use indexing and assignment to add 1 to each element of vector1 indexed by vector2
vector1[vector2] += 1

# Print the modified vector1
print(vector1)


[1 3 4 4 6]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [94]:
import numpy as np

# Define the vectors
X = np.array([1, 2, 3, 4, 5])
I = np.array([1, 2, 2, 4, 4])
F = np.zeros(5)

# Use indexing and assignment to accumulate the elements of X to F based on I
F[I] += X

# Print the modified F
print(F)


[0. 1. 3. 0. 5.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [95]:
import numpy as np

# Define the image
image = np.array([[[255, 0, 0], [255, 0, 0], [255, 0, 0]],
                  [[0, 255, 0], [0, 255, 0], [0, 255, 0]],
                  [[0, 0, 255], [0, 0, 255], [0, 0, 255]]], dtype=np.uint8)

# Flatten the image to a 1D array
image_flat = image.reshape(-1, 3)

# Use the unique function to find the unique colors
_, counts = np.unique(image_flat, return_counts=True, axis=0)

# Print the number of unique colors
print(counts.shape[0])



3


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [96]:
import numpy as np


array = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]],
                  [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])


result = np.sum(array, axis=(-2, -1))


print(result)



[[10 26]
 [42 58]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [97]:
import numpy as np

# Define the vectors
D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
S = np.array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1])

# Use the bincount function to get the counts and the indices of the unique elements in S
counts, indices = np.bincount(S)

# Use the unique function to get the unique elements in S
subsets = np.unique(S)

# Initialize an array to store the means of the subsets
means = np.zeros(subsets.shape[0])

# Loop over the unique elements in S
for i, subset in enumerate(subsets):
    # Use indexing to get the elements of D belonging to the current subset
    subset_values = D[S == subset]
    
    # Compute the mean of the subset values
    means[i] = np.mean(subset_values)

# Print the means
print(means)


ValueError: ignored

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [98]:
import numpy as np

# Define the matrices
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])

C = np.dot(A, B)

diagonal = np.diag(C)

print(diagonal)


[ 84 216 366]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
import numpy as np

V = np.array([1, 2, 3, 4, 5])

V_zeros = np.repeat(V, 4)

zeros = np.zeros(3)

V_new = np.concatenate([V_zeros, zeros])

print(V_new)


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [100]:
import numpy as np

# Define the arrays
A = np.random.rand(5, 5, 3)
B = np.random.rand(5, 5)

# Multiply A and B
C = A * B

# Print the resulting array
print(C)


ValueError: ignored

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [101]:
import numpy as np

# Define the array
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Original array:")
print(A)

# Swap the first and the last rows
A[[0, 2]] = A[[2, 0]]

print("\nSwapped array:")
print(A)


Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Swapped array:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [103]:
import numpy as np

# Define the triplets
triplets = np.array([[0, 1, 2], [0, 1, 3], [1, 2, 3], [2, 3, 4], [3, 4, 5], 
                     [4, 5, 6]])

lines = triplets[:, [0, 1, 1, 2, 2, 0]]

lines = lines.reshape(-1, 2)

lines = np.sort(lines, axis=1)

unique_lines, counts = np.unique(lines, return_counts=True, axis=0)

print(unique_lines)


[[0 1]
 [0 2]
 [0 3]
 [1 2]
 [1 3]
 [2 3]
 [2 4]
 [3 4]
 [3 5]
 [4 5]
 [4 6]
 [5 6]]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [1]:
import numpy as np

# Define the array C
C = np.array([2, 3, 0, 1, 0, 0, 0, 0, 2, 1])


n = len(C)


A = np.empty(n, dtype=int)


for i, c in enumerate(C):
   
    A[i:i+c] = i

print("Array A:")
print(A)


print("\nBincount of A:")
print(np.bincount(A))


Array A:
[0 1 1 3 0 0 0 0 8 9]

Bincount of A:
[5 2 0 1 0 0 0 0 1 1]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [2]:
import numpy as np

# Define the array
arr = np.array([1, 3, 2, 4, 5, 1, 3, 2, 4, 5])

window_size = 3

n = len(arr)

avgs = np.empty(n - window_size + 1)

for i in range(n - window_size + 1):
    
    avg = np.mean(arr[i:i+window_size])
    
    
    avgs[i] = avg

print("Averages:")
print(avgs)


Averages:
[2.         3.         3.66666667 3.33333333 3.         2.
 3.         3.66666667]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
import numpy as np

# Define a boolean array
bool_arr = np.array([True, False, True])

bool_arr = -bool_arr

print("Boolean array:")
print(bool_arr)

float_arr = np.array([1.0, 2.5, -3.0])

float_arr = -float_arr

print("\nFloat array:")
print(float_arr)

float_arr = ~float_arr

print("\nFloat array (using inplace negation):")
print(float_arr)


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [3]:
import numpy as np

A = np.array([[1,2,3],[2,3,4],[3,4,5]])

rank = np.linalg.matrix_rank(A)

print(rank)

2


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [4]:
import numpy as np

a =np.array([1,2,3,1,2,3,1,2,1,3,3,3,3])

values,counts = np.unique(a,return_counts=True)

index = np.argmax(counts)

print(values[index])


3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [6]:
import numpy as np

A = np.random.rand(10,10)

blocks= np.lib.stride_tricks.as_strided(A,shape=(8,8,3,3),
        strides=A.strides+A.strides)

blocks = blocks.reshape(8*8,3*3)
print(blocks)

[[0.8770664  0.50951637 0.72656364 0.61664663 0.10031848 0.72400006
  0.77240597 0.49444444 0.62671413]
 [0.50951637 0.72656364 0.24209516 0.10031848 0.72400006 0.1231071
  0.49444444 0.62671413 0.25398373]
 [0.72656364 0.24209516 0.94527409 0.72400006 0.1231071  0.20814887
  0.62671413 0.25398373 0.95506355]
 [0.24209516 0.94527409 0.75051521 0.1231071  0.20814887 0.2278247
  0.25398373 0.95506355 0.70605909]
 [0.94527409 0.75051521 0.83701937 0.20814887 0.2278247  0.30867708
  0.95506355 0.70605909 0.63906192]
 [0.75051521 0.83701937 0.51933715 0.2278247  0.30867708 0.44634166
  0.70605909 0.63906192 0.62854358]
 [0.83701937 0.51933715 0.56524038 0.30867708 0.44634166 0.59842837
  0.63906192 0.62854358 0.59499482]
 [0.51933715 0.56524038 0.46295383 0.44634166 0.59842837 0.94613306
  0.62854358 0.59499482 0.02611098]
 [0.61664663 0.10031848 0.72400006 0.77240597 0.49444444 0.62671413
  0.30579387 0.9212626  0.73101994]
 [0.10031848 0.72400006 0.1231071  0.49444444 0.62671413 0.2539837

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [7]:
import numpy as np

# Define the size of the grid
N = 10

# Define the initial state of the grid
grid = np.random.randint(2, size=(N, N))

# Define the rules of the game
def game_of_life(grid):
    # Pad the grid with zeros
    grid = np.pad(grid, 1, mode='constant')

    # Create a copy of the grid
    new_grid = grid.copy()

    # Iterate over the rows and columns
    for i in range(1, N+1):
        for j in range(1, N+1):
            # Get the 3x3 neighborhood around (i, j)
            neighbors = grid[i-1:i+2, j-1:j+2]

            # Apply the rules of the game
            if grid[i, j] == 1:
                if np.sum(neighbors) < 2 or np.sum(neighbors) > 3:
                    new_grid[i, j] = 0
            else:
                if np.sum(neighbors) == 3:
                    new_grid[i, j] = 1

    # Return the new grid
    return new_grid

# Run the game for 100 iterations
for i in range(100):
    grid = game_of_life(grid)

# Print the final state of the grid
print(grid)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [8]:
import numpy as np

arr = np.array([3,5,2,1,4])

sorted_arr = np.sort(arr)

n=3

largest_values = sorted_arr[-n:]

print(largest_values)


[3 4 5]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [9]:
import numpy as np

vectors = [np.array([1,2,3]),np.array([4,5]),np.array([6,7,8,9])]

coords = np.meshgrid(*vectors)

cartesian_product = np.vstack(coords).T

print(cartesian_product)  

[[[1 1 4 5 6 6]
  [2 2 4 5 6 6]
  [3 3 4 5 6 6]]

 [[1 1 4 5 7 7]
  [2 2 4 5 7 7]
  [3 3 4 5 7 7]]

 [[1 1 4 5 8 8]
  [2 2 4 5 8 8]
  [3 3 4 5 8 8]]

 [[1 1 4 5 9 9]
  [2 2 4 5 9 9]
  [3 3 4 5 9 9]]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [12]:
import numpy as np

data=([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])



names = ['field1','field2','field3',...]
dtypes =['int32','float32','float64',...]

rec_array = np.rec.fromarrays(data.T,names=names,dtypes=dtypes)

print(rec_array)

AttributeError: ignored

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [16]:
import numpy as np

Z = np.random.rand(10000000)

Z_cubed = Z**3
print(Z_cubed)

Z_cubed2=np.power(Z,3)
print(Z_cubed2)

Z_cubed3=np.multiply(Z,np.multiply(Z,Z))

print(Z_cubed3)


[5.42692482e-01 5.86838937e-02 4.91931767e-02 ... 1.56544078e-07
 1.35987397e-06 1.20706537e-01]
[5.42692482e-01 5.86838937e-02 4.91931767e-02 ... 1.56544078e-07
 1.35987397e-06 1.20706537e-01]
[5.42692482e-01 5.86838937e-02 4.91931767e-02 ... 1.56544078e-07
 1.35987397e-06 1.20706537e-01]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [18]:
import numpy as np

A = np.random.randint(10,size=(8,3))

B = np.random.randint(10,size= (2,2))

mask = np.all(np.isin(A,B),axis=1)

result =A[mask]

print(result)

[]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [19]:
import numpy as np

matrix = np.random.randint(10,size=(10,3))

mask = np.any(matrix[:,1:] !=matrix[:,:-1],axis=1)

result =matrix[mask]

print(result)


[[0 8 2]
 [8 3 5]
 [1 7 6]
 [6 0 7]
 [9 2 4]
 [2 7 6]
 [5 3 1]
 [5 8 1]
 [1 7 4]
 [1 6 8]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [20]:
import numpy as np

# Create a random vector of integers
vector = np.random.randint(10, size=10)

# Convert the vector to a matrix of binary representations
matrix = np.unpackbits(vector.astype(np.uint8), axis=1)

print(matrix)


AxisError: ignored

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [21]:
import numpy as np

# Create a random 2D array
array = np.random.randint(10, size=(5, 3))

# Extract unique rows and their indices
unique_rows, indices = np.unique(array, axis=0, return_index=True)

print(unique_rows)
print(indices)


[[2 2 0]
 [3 5 2]
 [6 0 1]
 [7 4 4]
 [7 7 4]]
[1 3 2 4 0]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
#inner
result = np.einsum("i,i->", A, B)

#outer
result = np.einsum("i,j->ij", A, B)

#sum

result = np.einsum("i->", A)

#mul
result = np.einsum("i->", A)


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [22]:
import numpy as np

# Create the X and Y vectors
X = np.array([0, 1, 2, 3, 4])
Y = np.array([0, 1, 4, 9, 16])

# Create the indices for the equidistant samples
num_samples = 10  # Number of samples to take along the path
indices = np.linspace(0, len(X) - 1, num_samples)

# Interpolate the X and Y vectors at the indices
X_samples = np.interp(indices, np.arange(len(X)), X)
Y_samples = np.interp(indices, np.arange(len(Y)), Y)

# The X_samples and Y_samples arrays now contain the equidistant samples of the path
print(X_samples)
print(Y_samples)


[0.         0.44444444 0.88888889 1.33333333 1.77777778 2.22222222
 2.66666667 3.11111111 3.55555556 4.        ]
[ 0.          0.44444444  0.88888889  2.          3.33333333  5.11111111
  7.33333333  9.77777778 12.88888889 16.        ]


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [23]:
import numpy as np

# Example input array
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

# Create mask for rows that are integer
mask_int = np.isinteger(X)

# Create mask for rows that sum to n
mask_sum = np.sum(X, axis=1) == n

# Combine masks
mask = np.logical_and(mask_int, mask_sum)

# Select rows that match mask
selected_rows = X[mask]


AttributeError: ignored

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [24]:
import numpy as np

# Example input array
X = np.array([1, 2, 3, 4, 5])

# Number of bootstrap samples
N = 1000

# Generate bootstrapped samples
samples = np.random.bootstrap(X, N)

# Compute means of samples
means = np.mean(samples, axis=1)

# Compute 95% confidence interval
conf_interval = np.percentile(means, [2.5, 97.5])
print(conf_interval)


AttributeError: ignored